name: Update Spotify Now Playing

on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes
  workflow_dispatch: # allows manual run from GitHub UI

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install requests

      # 4️⃣ Run Python script with Spotify secrets
      - name: Run script
        run: python nowplaying.py
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}

      # 5️⃣ Update README placeholder
      - name: Update README
        run: |
          NOWPLAYING=$(cat spotify.txt)
          sed -i "s|<!-- SPOTIFY -->.*<!-- END_SPOTIFY -->|<!-- SPOTIFY -->$NOWPLAYING<!-- END_SPOTIFY -->|" README.md

      # 6️⃣ Commit and push changes
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Update Spotify now playing" || echo "No changes to commit"
          git push
